[package]
name = "security"
version = "0.1.0"
edition = "2024"

[dependencies]
argon2 = "0.5.3"
chrono = { workspace = true }
domain = { workspace = true }
hmac = "0.12.1"
jwt = "0.16.0"
password-hash = "0.5.0"
serde = { workspace = true }
sha2 = "0.10.9"
