[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = { workspace = true }
domain = { workspace = true }
dtos = { workspace = true }
repository = { workspace = true }
services = { workspace = true }
